### PR TITLE
Add preliminary apprentice color theme

### PR DESCRIPTION
**Pull request by non-Jedi**
It's a bit rough at the moment, but it's a start at least, and this way it's available to people who are better at color stuff who might want to improve it. Feel free to reject if it's too ugly. ;)

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

Thanks, looks like you implemented it just the way other themes are, which is great.  I don't have an opinion on the color scheme; I figure that as long as it's implemented properly and is an actual theme, there's no reason not to merge it.

@jgkamat @The-Compiler What do you guys think?

**Comment by alphapapa** [comment]
@non-Jedi Would you add yourself to the credits section of the readme?  Then I think this is ready to merge.  Thanks.

**Comment by non-Jedi** [comment]
Done

**Comment by alphapapa** [comment]
Great, thanks.  I'll merge and then adjust the TOC.  Welcome to the project.

**Pull request merged**
