### PR TITLE
Implement simple release script

### PR DESCRIPTION
**Pull request by jgkamat**
- Runs make
- Creates a zip release file
- Creates a github release at current commit (draft)
- Uploads zip to github releases

Right now this points to my repo, the ENV vars at the top need to be updated to point to this repo instead if we decide to move forward.

I'm not sure if a github release or a 'generated files' branch is better still. If you think that the 'generated-files' branch is a better idea, let me know and I'll write that (which shouldn't be too hard). 

See #22

### CODE REVIEW

**Comment by cal2195** [comment]
I personally think github releases make more sense - also allows for easy one liner with wget on the read me to download all themes for end users! :)

**Comment by alphapapa** [comment]
Hey Jay, that looks really good, great job.  Thanks for taking care of that.

To be honest, I'm not completely sold on the idea of doing zip-file releases or using a separate branch for CSS files.  But it doesn't cost us anything to try them, so if you think it's a good idea, I see no reason not to give it a try, especially since you've made this.  :)

Do you want to go ahead and merge this and do some test releases?

**Comment by jgkamat** [comment]
> Hey Jay, that looks really good, great job. Thanks for taking care of that.

Wow, thanks! :). I don't think it's that good to be honest (it's a bit hacky), but we'll see how it works.

> Should we have a make release target for this?

Yup, I'll add that in the next commit

> The make clean rule is probably a good idea. Does rm need to be called with -f too?

In the makefile rule, I prefixed the command with `-`, which *should* allow it to keep running even if it fails. I don't like the `f` option since it dosen't alert when it fails, but I thought about it, and I think that's fine, so I'll remove the `-` and add the `-f` flag :).

**Comment by alphapapa** [comment]
> Wow, thanks! :). I don't think it's that good to be honest (it's a bit hacky), but we'll see how it works.

Well, you seemed to do a thorough job of checking data beforehand, checking for required programs, and most people probably wouldn't have.  :)

> In the makefile rule, I prefixed the command with -, which should allow it to keep running even if it fails. I don't like the f option since it dosen't alert when it fails, but I thought about it, and I think that's fine, so I'll remove the - and add the -f flag :).

I'm not an expert, but I think `rm -rf` is standard for clean-type rules in makefiles.  I think it won't even work without the `-f` in most cases.  So I think that should do it.  As long as the target directory is hard-coded, it shouldn't cause any problems.

**Comment by jgkamat** [comment]
I'm going to go ahead and merge this, since it dosen't break anything, and I want to start preparing to 'release' multi-theme. :)

**Pull request merged**
