### PR TITLE
Add GPL license

### PR DESCRIPTION
**Pull request by The-Compiler**
As mentioned in https://github.com/alphapapa/solarized-everything-css/issues/22#issuecomment-337318063

@alphapapa and @jgkamat already mentioned they're fine with the GPL - @RealyUniqueName @neeasade @cal2195 Are you all okay with licensing your contributions under the GPL?

### CODE REVIEW

**Comment by cal2195** [comment]
Works for me! 😄

**Comment by RealyUniqueName** [comment]
I'm ok

**Comment by neeasade** [comment]
good with me

**Comment by The-Compiler** [comment]
Looks like this works out for everyone then, thanks for the quick answers! I'll let @alphapapa merge this one though :wink:

**Comment by alphapapa** [comment]
Thanks, Florian!

**Pull request merged**
