### PR TITLE
make check color consistent

### PR DESCRIPTION
**Pull request by vcfvct**
### before
check-before

### after
check-after

Please let me know if you have any concerns. Thanks.

### CODE REVIEW

**Comment by jgkamat** [comment]
> diff --git a/sites/github.styl b/sites/github.styl
> index fe16019..17bafa6 100644
> --- a/sites/github.styl
> +++ b/sites/github.styl
> @@ -649,7 +649,7 @@ a.label
>  .octicon-x
>      color red
>  .octicon-check
> -    color green
> +    color black

I think octicon-check is used for the CI checks as well, so we can't do
something like this or the CI checks (and checks used in other places) will
become black.

>  .octicon-primitive-dot
>      color yellow

**Comment by vcfvct** [comment]
@jgkamat , good point, so any suggest color to fix this?

**Comment by jgkamat** [comment]
> @jgkamat , good point, so any suggest color to fix this?

I'm not actually sure. we could look deeper to see how exactly github styles
the two checks differently, since there must be a difference in their CSS, or
we could dim the color a little bit on our end so the green isn't exactly the
same as a hack :P.

Of course, the first solution is ideal, but requires a little bit of digging
to figure out what's going on on github's side.

**Comment by The-Compiler** [comment]
Maybe style the `div` instead, e.g. the `.completeness-indicator` class?

**Comment by alphapapa** [comment]
Thanks for looking into this.  Small suggestion: black is probably not the best color to use, as it clashes with the rest of the theme.  We should probably use the default text color, as long as it has enough contrast.  If not, it could be darkened slightly with a Stylus filter.

**Pull request closed without merging**
