### PR TITLE
[github] Renaming issues, changing assignees, reviewers

### PR DESCRIPTION
**Pull request by RealyUniqueName**
# Renaming issues
Before:

After:

# Assignees, reviewers
Before:

After:

### CODE REVIEW

**Comment by jgkamat** [comment]
Hmm, I think that I fixed these issues in https://github.com/alphapapa/solarized-everything-css/pull/32, but I forgot to re-generate the CSS as part of the PR. I think that if you just regenerate the CSS (remove the changes in the `styl` files), these should be properly visible. Can you confirm that for me (and if so, I'll merge the updated css).

**Comment by alphapapa** [comment]
@jgkamat Yes, the changes to `github.styl` do not reflect all the changes in the generated CSS, so the CSS changes shouldn't be merged.  I think it's okay to sometimes commit the generated CSS separately, but in that case, the `styl` changes should be committed first.

@RealyUniqueName Did you edit the CSS directly?  Thank you for the fixes, anyway.

@jgkamat Also, I guess it's past time for us to do something about the `multi-theme` branch, so we don't have to keep rebasing it on top of fixes like this.  :)  What do you think?

**Comment by jgkamat** [comment]
Ah, I didn't notice this comment when preparing #35, I want to try to 'release' multi theme, so #35 exists now :smile:. I need to clean it up though, but I think it should be good to go soon!

**Comment by RealyUniqueName** [comment]
> @RealyUniqueName Did you edit the CSS directly? Thank you for the fixes, anyway.

No, I didn't. The only file I edited is `github.styl`. But after `make` stackexchange style became empty, and I didn't commit it.

>  Hmm, I think that I fixed these issues in #32 (...) Can you confirm that for me

I confirm. Closing this PR in favor of #32

**Pull request closed without merging**
