### PR TITLE
Replace dark gray for more contrast

### PR DESCRIPTION
**Pull request by RealyUniqueName**
# Repo description
before after

# Commit details
before after

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Thanks to jpeg glitches that dark gray in the original screenshots looks more readable than it is )

**Comment by The-Compiler** [comment]
You should edit `sites/github.styl`, not the "compiled" css file.

**Comment by RealyUniqueName** [comment]
Done.

**Comment by alphapapa** [comment]
@RealyUniqueName Thanks very much for these improvements!

@The-Compiler Thanks very much for your help here.  Would you be interested in co-maintaining this repo?

**Comment by The-Compiler** [comment]
@alphapapa I'd be happy to help with reviewing stuff! I'll still open PRs for my own contributions though, and of course my time is rather limited, but count me in!

**Comment by alphapapa** [comment]
Great, any help is appreciated, and you clearly know what you're doing.  Thanks.  :)

**Pull request merged**
